#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
批量更新剧本时长
需求：
大宴之上：9h+
万仞青山听水寒：8-9h
流芳：9h+
窃云台：8h+
请君入瓮：9-10h
阙落：8-9h
如故：12h+
壁上观：9-10h
同归：6-7h
"""

import re

def update_script_durations(file_path):
    """批量修改剧本时长"""
    
    with open(file_path, 'r', encoding='utf-8') as f:
        content = f.read()
    
    # 定义剧本时长更新映射
    duration_updates = {
        '大宴之上': r'<h2 class="script-title">大宴之上</h2>\s*<p class="script-subtitle">6人古风变格情感本</p>\s*<div class="script-details">[^{]+<div class="detail-label">⏱ 时长</div>\s*<div class="detail-value">[^<]+</div>',
        '万仞青山听水寒': r'<h2 class="script-title">万仞青山听水寒</h2>\s*<p class="script-subtitle">6人古风仙侠情感本</p>\s*<div class="script-details">[^<]+<div class="detail-label">⏱ 时长</div>\s*<div class="detail-value">8-9h</div>',
        '流芳': r'<h2 class="script-title">流芳</h2>[\s\S]*?<div class="detail-label">⏱ 时长</div>\s*<div class="detail-value">[^<]+</div>',
        '窃云台': r'<h2 class="script-title">窃云台</h2>[\s\S]*?<div class="detail-label">⏱ 时长</div>\s*<div class="detail-value">[^<]+</div>',
        '请君入瓮': r'<h2 class="script-title">请君入瓮</h2>[\s\S]*?<div class="detail-label">⏱ 时长</div>\s*<div class="detail-value">[^<]+</div>',
        '阙落': r'<h2 class="script-title">阙落</h2>[\s\S]*?<div class="detail-label">⏱ 时长</div>\s*<div class="detail-value">[^<]+</div>',
        '如故': r'<h2 class="script-title">如故</h2>[\s\S]*?<div class="detail-label">⏱ 时长</div>\s*<div class="detail-value">[^<]+</div>',
        '壁上观': r'<h2 class="script-title">壁上观</h2>[\s\S]*?<div class="detail-label">⏱ 时长</div>\s*<div class="detail-value">[^<]+</div>',
        '同归': r'<h2 class="script-title">同归</h2>[\s\S]*?<div class="detail-label">⏱ 时长</div>\s*<div class="detail-value">[^<]+</div>'
    }
    
    # 定义新时长替换函数
    def replace_duration(match):
        # 直接匹配替换时长部分
        old_text = match.group(0)
        # 找到时长部分并替换
        new_text = re.sub(r'<div class="detail-value">[^<]+</div>', '<div class="detail-value">NEW_DURATION</div>', old_text)
        return new_text
    
    # 直接使用简单的字符串替换方式
    updates = [
        ("流芳", "<!-- 流芳 -->\n            <div class=\"script-card\">\n                <span class=\"difficulty 进阶\">进阶</span>\n                <div style=\"position: absolute; bottom: 20px; right: 20px; width: 30px; height: 30px; background: rgba(100, 100, 100, 0.1); border-radius: 6px; display: flex; align-items: center; justify-content: center; border: 1px solid rgba(100, 100, 100, 0.2); z-index: 1; opacity: 0.5; pointer-events: none;\">\n                    <span style=\"font-size: 0.85rem;\">📜</span>\n                </div>\n                <h2 class=\"script-title\">流芳</h2>\n                <p class=\"script-subtitle\">6人历史改编家国正剧本</p>\n                <div class=\"script-details\">\n                    <div class=\"detail-item\">\n                        <div class=\"detail-label\">👥 人员</div>\n                        <div class=\"detail-value\">3男3女</div>\n                    </div>\n                    <div class=\"detail-item\">\n                        <div class=\"detail-label\">⏱ 时长</div>\n                        <div class=\"detail-value\">5-6h</div>", "<!-- 流芳 -->\n            <div class=\"script-card\">\n                <span class=\"difficulty 进阶\">进阶</span>\n                <div style=\"position: absolute; bottom: 20px; right: 20px; width: 30px; height: 30px; background: rgba(100, 100, 100, 0.1); border-radius: 6px; display: flex; align-items: center; justify-content: center; border: 1px solid rgba(100, 100, 100, 0.2); z-index: 1; opacity: 0.5; pointer-events: none;\">\n                    <span style=\"font-size: 0.85rem;\">📜</span>\n                </div>\n                <h2 class=\"script-title\">流芳</h2>\n                <p class=\"script-subtitle\">6人历史改编家国正剧本</p>\n                <div class=\"script-details\">\n                    <div class=\"detail-item\">\n                        <div class=\"detail-label\">👥 人员</div>\n                        <div class=\"detail-value\">3男3女</div>\n                    </div>\n                    <div class=\"detail-item\">\n                        <div class=\"detail-label\">⏱ 时长</div>\n                        <div class=\"detail-value\">9h+</div>"),
        ("窃云台", "<!-- 窃云台 -->\n            <div class=\"script-card\">\n                <span class=\"difficulty 进阶\">进阶</span>\n                <div style=\"position: absolute; bottom: 20px; right: 20px; width: 30px; height: 30px; background: rgba(100, 100, 100, 0.1); border-radius: 6px; display: flex; align-items: center; justify-content: center; border: 1px solid rgba(100, 100, 100, 0.2); z-index: 1; opacity: 0.5; pointer-events: none;\">\n                    <span style=\"font-size: 0.85rem;\">👑</span>\n                </div>\n                <h2 class=\"script-title\">窃云台</h2>\n                <p class=\"script-subtitle\">6人古风权谋情感本</p>\n                <div class=\"script-details\">\n                    <div class=\"detail-item\">\n                        <div class=\"detail-label\">👥 人员</div>\n                        <div class=\"detail-value\">3男3女</div>\n                    </div>\n                    <div class=\"detail-item\">\n                        <div class=\"detail-label\">⏱ 时长</div>\n                        <div class=\"detail-value\">6-7h</div>", "<!-- 窃云台 -->\n            <div class=\"script-card\">\n                <span class=\"difficulty 进阶\">进阶</span>\n                <div style=\"position: absolute; bottom: 20px; right: 20px; width: 30px; height: 30px; background: rgba(100, 100, 100, 0.1); border-radius: 6px; display: flex; align-items: center; justify-content: center; border: 1px solid rgba(100, 100, 100, 0.2); z-index: 1; opacity: 0.5; pointer-events: none;\">\n                    <span style=\"font-size: 0.85rem;\">👑</span>\n                </div>\n                <h2 class=\"script-title\">窃云台</h2>\n                <p class=\"script-subtitle\">6人古风权谋情感本</p>\n                <div class=\"script-details\">\n                    <div class=\"detail-item\">\n                        <div class=\"detail-label\">👥 人员</div>\n                        <div class=\"detail-value\">3男3女</div>\n                    </div>\n                    <div class=\"detail-item\">\n                        <div class=\"detail-label\">⏱ 时长</div>\n                        <div class=\"detail-value\">8h+</div>"),
        ("请君入瓮", "<!-- 请君入瓮 -->\n            <div class=\"script-card\">\n                <span class=\"difficulty 标准\">标准</span>\n                <div style=\"position: absolute; bottom: 20px; right: 20px; width: 30px; height: 30px; background: rgba(100, 100, 100, 0.1); border-radius: 6px; display: flex; align-items: center; justify-content: center; border: 1px solid rgba(100, 100, 100, 0.2); z-index: 1; opacity: 0.5; pointer-events: none;\">\n                    <span style=\"font-size: 0.85rem;\">📖</span>\n                </div>\n                <h2 class=\"script-title\">请君入瓮</h2>\n                <p class=\"script-subtitle\">6人古风穿书情感架空本</p>\n                <div class=\"script-details\">\n                    <div class=\"detail-item\">\n                        <div class=\"detail-label\">👥 人员</div>\n                        <div class=\"detail-value\">3男3女</div>\n                    </div>\n                    <div class=\"detail-item\">\n                        <div class=\"detail-label\">⏱ 时长</div>\n                        <div class=\"detail-value\">5-6h</div>", "<!-- 请君入瓮 -->\n            <div class=\"script-card\">\n                <span class=\"difficulty 标准\">标准</span>\n                <div style=\"position: absolute; bottom: 20px; right: 20px; width: 30px; height: 30px; background: rgba(100, 100, 100, 0.1); border-radius: 6px; display: flex; align-items: center; justify-content: center; border: 1px solid rgba(100, 100, 100, 0.2); z-index: 1; opacity: 0.5; pointer-events: none;\">\n                    <span style=\"font-size: 0.85rem;\">📖</span>\n                </div>\n                <h2 class=\"script-title\">请君入瓮</h2>\n                <p class=\"script-subtitle\">6人古风穿书情感架空本</p>\n                <div class=\"script-details\">\n                    <div class=\"detail-item\">\n                        <div class=\"detail-label\">👥 人员</div>\n                        <div class=\"detail-value\">3男3女</div>\n                    </div>\n                    <div class=\"detail-item\">\n                        <div class=\"detail-label\">⏱ 时长</div>\n                        <div class=\"detail-value\">9-10h</div>"),
        ("阙落", "<!-- 三体·阙落 -->\n            <div class=\"script-card\">\n                <span class=\"difficulty 高阶\">高阶</span>\n                <div style=\"position: absolute; bottom: 20px; right: 20px; width: 30px; height: 30px; background: rgba(100, 100, 100, 0.1); border-radius: 6px; display: flex; align-items: center; justify-content: center; border: 1px solid rgba(100, 100, 100, 0.2); z-index: 1; opacity: 0.5; pointer-events: none;\">\n                    <span style=\"font-size: 0.85rem;\">🌌</span>\n                </div>\n                <h2 class=\"script-title\">阙落</h2>\n                <p class=\"script-subtitle\">6人古风架空情感本</p>\n                <div class=\"script-details\">\n                    <div class=\"detail-item\">\n                        <div class=\"detail-label\">👥 人员</div>\n                        <div class=\"detail-value\">4男2女</div>\n                    </div>\n                    <div class=\"detail-item\">\n                        <div class=\"detail-label\">⏱ 时长</div>\n                        <div class=\"detail-value\">6-7h</div>", "<!-- 三体·阙落 -->\n            <div class=\"script-card\">\n                <span class=\"difficulty 高阶\">高阶</span>\n                <div style=\"position: absolute; bottom: 20px; right: 20px; width: 30px; height: 30px; background: rgba(100, 100, 100, 0.1); border-radius: 6px; display: flex; align-items: center; justify-content: center; border: 1px solid rgba(100, 100, 100, 0.2); z-index: 1; opacity: 0.5; pointer-events: none;\">\n                    <span style=\"font-size: 0.85rem;\">🌌</span>\n                </div>\n                <h2 class=\"script-title\">阙落</h2>\n                <p class=\"script-subtitle\">6人古风架空情感本</p>\n                <div class=\"script-details\">\n                    <div class=\"detail-item\">\n                        <div class=\"detail-label\">👥 人员</div>\n                        <div class=\"detail-value\">4男2女</div>\n                    </div>\n                    <div class=\"detail-item\">\n                        <div class=\"detail-label\">⏱ 时长</div>\n                        <div class=\"detail-value\">8-9h</div>"),
        ("如故", "<!-- 三体·如故 -->\n            <div class=\"script-card\">\n                <span class=\"difficulty 进阶\">进阶</span>\n                <div style=\"position: absolute; bottom: 20px; right: 20px; width: 30px; height: 30px; background: rgba(100, 100, 100, 0.1); border-radius: 6px; display: flex; align-items: center; justify-content: center; border: 1px solid rgba(100, 100, 100, 0.2); z-index: 1; opacity: 0.5; pointer-events: none;\">\n                    <span style=\"font-size: 0.85rem;\">🌠</span>\n                </div>\n                <h2 class=\"script-title\">如故</h2>\n                <p class=\"script-subtitle\">6人古风架空情感本</p>\n                <div class=\"script-details\">\n                    <div class=\"detail-item\">\n                        <div class=\"detail-label\">👥 人员</div>\n                        <div class=\"detail-value\">3男3女</div>\n                    </div>\n                    <div class=\"detail-item\">\n                        <div class=\"detail-label\">⏱ 时长</div>\n                        <div class=\"detail-value\">5-6h</div>", "<!-- 三体·如故 -->\n            <div class=\"script-card\">\n                <span class=\"difficulty 进阶\">进阶</span>\n                <div style=\"position: absolute; bottom: 20px; right: 20px; width: 30px; height: 30px; background: rgba(100, 100, 100, 0.1); border-radius: 6px; display: flex; align-items: center; justify-content: center; border: 1px solid rgba(100, 100, 100, 0.2); z-index: 1; opacity: 0.5; pointer-events: none;\">\n                    <span style=\"font-size: 0.85rem;\">🌠</span>\n                </div>\n                <h2 class=\"script-title\">如故</h2>\n                <p class=\"script-subtitle\">6人古风架空情感本</p>\n                <div class=\"script-details\">\n                    <div class=\"detail-item\">\n                        <div class=\"detail-label\">👥 人员</div>\n                        <div class=\"detail-value\">3男3女</div>\n                    </div>\n                    <div class=\"detail-item\">\n                        <div class=\"detail-label\">⏱ 时长</div>\n                        <div class=\"detail-value\">12h+</div>"),
        ("壁上观", "<!-- 壁上观 -->\n            <div class=\"script-card\">\n                <span class=\"difficulty 进阶\">进阶</span>\n                <div style=\"position: absolute; bottom: 20px; right: 20px; width: 30px; height: 30px; background: rgba(100, 100, 100, 0.1); border-radius: 6px; display: flex; align-items: center; justify-content: center; border: 1px solid rgba(100, 100, 100, 0.2); z-index: 1; opacity: 0.5; pointer-events: none;\">\n                    <span style=\"font-size: 0.85rem;\">🧱</span>\n                </div>\n                <h2 class=\"script-title\">壁上观</h2>\n                <p class=\"script-subtitle\">6人西游改编古风情感本</p>\n                <div class=\"script-details\">\n                    <div class=\"detail-item\">\n                        <div class=\"detail-label\">👥 人员</div>\n                        <div class=\"detail-value\">3男3女</div>\n                    </div>\n                    <div class=\"detail-item\">\n                        <div class=\"detail-label\">⏱ 时长</div>\n                        <div class=\"detail-value\">5-6h</div>", "<!-- 壁上观 -->\n            <div class=\"script-card\">\n                <span class=\"difficulty 进阶\">进阶</span>\n                <div style=\"position: absolute; bottom: 20px; right: 20px; width: 30px; height: 30px; background: rgba(100, 100, 100, 0.1); border-radius: 6px; display: flex; align-items: center; justify-content: center; border: 1px solid rgba(100, 100, 100, 0.2); z-index: 1; opacity: 0.5; pointer-events: none;\">\n                    <span style=\"font-size: 0.85rem;\">🧱</span>\n                </div>\n                <h2 class=\"script-title\">壁上观</h2>\n                <p class=\"script-subtitle\">6人西游改编古风情感本</p>\n                <div class=\"script-details\">\n                    <div class=\"detail-item\">\n                        <div class=\"detail-label\">👥 人员</div>\n                        <div class=\"detail-value\">3男3女</div>\n                    </div>\n                    <div class=\"detail-item\">\n                        <div class=\"detail-label\">⏱ 时长</div>\n                        <div class=\"detail-value\">9-10h</div>"),
        ("同归", "<!-- 同归 -->\n            <div class=\"script-card\">\n                <span class=\"difficulty 标准\">标准</span>\n                <div style=\"position: absolute; bottom: 20px; right: 20px; width: 30px; height: 30px; background: rgba(100, 100, 100, 0.1); border-radius: 6px; display: flex; align-items: center; justify-content: center; border: 1px solid rgba(100, 100, 100, 0.2); z-index: 1; opacity: 0.5; pointer-events: none;\">\n                    <span style=\"font-size: 0.85rem;\">🧭</span>\n                </div>\n                <h2 class=\"script-title\">同归</h2>\n                <p class=\"script-subtitle\">6人古风情感本</p>\n                <div class=\"script-details\">\n                    <div class=\"detail-item\">\n                        <div class=\"detail-label\">👥 人员</div>\n                        <div class=\"detail-value\">3男3女</div>\n                    </div>\n                    <div class=\"detail-item\">\n                        <div class=\"detail-label\">⏱ 时长</div>\n                        <div class=\"detail-value\">4-5h</div>", "<!-- 同归 -->\n            <div class=\"script-card\">\n                <span class=\"difficulty 标准\">标准</span>\n                <div style=\"position: absolute; bottom: 20px; right: 20px; width: 30px; height: 30px; background: rgba(100, 100, 100, 0.1); border-radius: 6px; display: flex; align-items: center; justify-content: center; border: 1px solid rgba(100, 100, 100, 0.2); z-index: 1; opacity: 0.5; pointer-events: none;\">\n                    <span style=\"font-size: 0.85rem;\">🧭</span>\n                </div>\n                <h2 class=\"script-title\">同归</h2>\n                <p class=\"script-subtitle\">6人古风情感本</p>\n                <div class=\"script-details\">\n                    <div class=\"detail-item\">\n                        <div class=\"detail-label\">👥 人员</div>\n                        <div class=\"detail-value\">3男3女</div>\n                    </div>\n                    <div class=\"detail-item\">\n                        <div class=\"detail-label\">⏱ 时长</div>\n                        <div class=\"detail-value\">6-7h</div>")
    ]
    
    updated = False
    for script_name, old_text, new_text in updates:
        if old_text in content:
            content = content.replace(old_text, new_text)
            print(f"✅ 已修改 {script_name} 时长")
            updated = True
        else:
            print(f"⚠️  未找到 {script_name} 的完整文本，尝试其他方法")
    
    if updated:
        with open(file_path, 'w', encoding='utf-8') as f:
            f.write(content)
        print(f"✅ 时长修改完成，文件已保存: {file_path}")
    else:
        print("❌ 未找到任何匹配的剧本时长信息")
        
    return updated

def main():
    html_file = 'quick-site.html'
    if update_script_durations(html_file):
        print("🎉 所有剧本时长修改完成！")
    else:
        print("检查HTML文件内容是否正确")

if __name__ == '__main__':
    main()